name: hCAVIAR
channels:
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - gcta=1.94.1
  - importlib-metadata=8.6.1
  - jax=0.5.2
  - jaxlib=0.5.2
  - libabseil=20250127.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran
  - libgfortran5=14.2.0
  - libgrpc=1.71.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - ml_dtypes=0.5.1
  - ncurses=6.5
  - numpy=2.2.4
  - openssl=3.4.1
  - opt_einsum=3.4.0
  - pandas=2.2.3
  - pip=25.0.1
  - plink=1.90b7.7
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2024.1
  - re2=2024.07.02
  - readline=8.2
  - scipy=1.15.2
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025b
  - zipp=3.21.0
