name: SUM2HLA_gpu
channels:
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - icu=75.1
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - jax=0.4.14
  - jaxlib=0.4.14=cuda112py310h8c6a9b4_201
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libabseil=20230125.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.17.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.56.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopenssl-static=3.6.0
  - libpng=1.6.50
  - libprotobuf=4.23.3
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mariadb-connector-c=3.4.7
  - ml_dtypes=0.5.1
  - mysql-connector-c=6.1.11
  - nccl=2.27.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - pandas=2.3.3
  - pip=25.3
  - plink=1.90b7.7
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - re2=2023.03.02
  - readline=8.2
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - ucsc-liftover=482
  - wheel=0.45.1
  - zipp=3.23.0
  - zstd=1.5.7
